knp_paginator:
    page_range: 5                      # počet stránok v navigačnom menu
    default_options:
        page_name: page                # meno GET parametra pre číslo stránky
        sort_field_name: sort          # meno GET parametra pre pole na triedenie
        sort_direction_name: direction # meno GET parametra pre smer triedenia
        distinct: true                 # zostaviť dotaz s DISTINCT kľúčom
